import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Sidebar } from '../Components/Sidebar'
import styles from '../styles/Home.module.css'
import { ToDo } from '../Components/to-do'
import {Gym} from '../Components/Gym'
import { GymList } from '../Components/GymList'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GymRNK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <Sidebar/>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to GymRank
        </h1>

        <div className={styles.grid}>
        <GymList/>
        
        </div>
      </main>
    </>
  )
}

export default Home
